name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install
        env:
          CI: true

      - name: Set up Environment Variables
        run: |
          echo "PORT=${{ secrets.PORT }}" >> $GITHUB_ENV
          echo "MONGODB_URI=${{ secrets.mongodb_uri }}" >> $GITHUB_ENV
          echo "MONGODB_URI_TEST=${{ secrets.mongodb_uri_test }}" >> $GITHUB_ENV
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }}" >> $GITHUB_ENV
          echo "EMAIL_APP_PASSWORD=${{ secrets.EMAIL_APP_PASSWORD }}" >> $GITHUB_ENV
          echo "EMAIL_NAME=${{ secrets.EMAIL_NAME }}" >> $GITHUB_ENV
          echo "VNP_TMN_CODE=${{ secrets.VNP_TMN_CODE }}" >> $GITHUB_ENV
          echo "VNP_HASH_SECRET=${{ secrets.VNP_HASH_SECRET }}" >> $GITHUB_ENV
          echo "VNP_URL=${{ secrets.VNP_URL }}" >> $GITHUB_ENV
          echo "VNP_RETURN_URL=${{ secrets.VNP_RETURN_URL }}" >> $GITHUB_ENV

      - name: Run Tests
        run: npm test
        env:
          CI: true

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
