name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install
        env:
          CI: true

      - name: Install Chai
        run: npm install chai
        env:
          CI: true

      - name: Install Chai-Http
        run: npm install chai-http
        env:
          CI: true

      - name: Install Argon2
        run: npm install argon2
        env:
          CI: true

      - name: Install JSONWebToken
        run: npm install jsonwebtoken
        env:
          CI: true

      - name: Install dotenv
        run: npm install dotenv
        env:
          CI: true

      - name: Install Moment-Timezone
        run: npm install moment-timezone
        env:
          CI: true

      - name: Run Tests
        run: npm test
        env:
          CI: true

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
